In [140]:
import pandas as pd
import numpy as np

fukuoka = pd.read_csv("Fukuoka_hotel_data.csv")
osaka = pd.read_csv("Osaka_hotel_data.csv")
fukuoka

,month,day,hotel_name,price,hotel_star,review_score,hotel_URL
0,7,24,더 라이프 호스텔 & 바 라운지,"22,001원~",1성급,8.0,https://hotels.naver.com/item?hotelFileName=ho...
1,7,24,스탠드 바이 미,"16,494원~",1성급,6.0,https://hotels.naver.com/item?hotelFileName=ho...
2,7,24,잼 호스텔 하카타 스테이션 프론트,"28,888원~",1성급,7.6,https://hotels.naver.com/item?hotelFileName=ho...
3,7,24,커먼 드 - 호스텔 & 바,"29,267원~",1성급,8.3,https://hotels.naver.com/item?hotelFileName=ho...
4,7,24,게스트 하우스 야스라기 하카타에키마에,"24,461원~",1성급,7.7,https://hotels.naver.com/item?hotelFileName=ho...
...,...,...,...,...,...,...,...
1055,8,4,더 브렉퍼스트 호텔 후쿠오카 텐진,"201,852원~",3성급,8.2,https://hotels.naver.com/item?hotelFileName=ho...
1056,8,4,니시테츠 호텔 크룸 하카타,"208,678원~",3성급,8.4,https://hotels.naver.com/item?hotelFileName=ho...
1057,8,4,하마코야,"209,068원~",3성급,9.2,https://hotels.naver.com/item?hotelFileName=ho...
1058,8,4,하카타 도큐 레이 호텔,"213,764원~",3성급,8.3,https://hotels.naver.com/item?hotelFileName=ho...
1059,8,4,라이프 텐진 후쿠오카,"215,784원~",3성급,8.6,https://hotels.naver.com/item?hotelFileName=ho...

In [141]:
def engineering(data):
    # month + day = datetime 변경
    data['date'] = pd.to_datetime('2023-' + data['month'].astype(str) + '-' + data['day'].astype(str))
    data.drop(columns=['month', 'day'], inplace=True)
    # price 컬럼 원~ 제거후 int 변경
    data['price'] = data['price'].replace({'[,]' : '', '[원~]': ''}, regex=True).astype('int')
    # 호텔 등급 성급 제거 후 int 변경
    data['hotel_star'] = data['hotel_star'].replace({'[성급]': ''}, regex=True).astype('int')

engineering(fukuoka)
engineering(osaka)

In [142]:
fukuoka = fukuoka[['date', 'hotel_name', 'price', 'hotel_star', 'review_score', 'hotel_URL']]
osaka = osaka[['date', 'hotel_name', 'price', 'hotel_star', 'review_score', 'hotel_URL']]
osaka = osaka.replace('평점없음', np.nan)
fukuoka

,date,hotel_name,price,hotel_star,review_score,hotel_URL
0,2023-07-24,더 라이프 호스텔 & 바 라운지,22001,1,8.0,https://hotels.naver.com/item?hotelFileName=ho...
1,2023-07-24,스탠드 바이 미,16494,1,6.0,https://hotels.naver.com/item?hotelFileName=ho...
2,2023-07-24,잼 호스텔 하카타 스테이션 프론트,28888,1,7.6,https://hotels.naver.com/item?hotelFileName=ho...
3,2023-07-24,커먼 드 - 호스텔 & 바,29267,1,8.3,https://hotels.naver.com/item?hotelFileName=ho...
4,2023-07-24,게스트 하우스 야스라기 하카타에키마에,24461,1,7.7,https://hotels.naver.com/item?hotelFileName=ho...
...,...,...,...,...,...,...
1055,2023-08-04,더 브렉퍼스트 호텔 후쿠오카 텐진,201852,3,8.2,https://hotels.naver.com/item?hotelFileName=ho...
1056,2023-08-04,니시테츠 호텔 크룸 하카타,208678,3,8.4,https://hotels.naver.com/item?hotelFileName=ho...
1057,2023-08-04,하마코야,209068,3,9.2,https://hotels.naver.com/item?hotelFileName=ho...
1058,2023-08-04,하카타 도큐 레이 호텔,213764,3,8.3,https://hotels.naver.com/item?hotelFileName=ho...
1059,2023-08-04,라이프 텐진 후쿠오카,215784,3,8.6,https://hotels.naver.com/item?hotelFileName=ho...

In [143]:
fukuoka.to_csv('./Fukuoka_hotel.csv')
osaka.to_csv('./Osaka_hotel.csv')